# Generated by Django 4.0.1 on 2022-01-31 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=50, verbose_name='გვარი')),
                ('date_of_birth', models.DateField(verbose_name='დაბადების თარიღი')),
            ],
            options={
                'verbose_name': 'ავტორები',
            },
        ),
        migrations.CreateModel(
            name='BookName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='სახელი')),
                ('image', models.ImageField(upload_to='images', verbose_name='სურათი')),
                ('description', models.TextField(verbose_name='აღწერა')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='ავტორი')),
            ],
            options={
                'verbose_name': 'წიგნი',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='პარაგრაფის სათაური')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookname', verbose_name='წიგნი')),
            ],
            options={
                'verbose_name': 'პარაგრაფები',
            },
        ),
        migrations.CreateModel(
            name='ParagraphStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(verbose_name='ამბავი')),
                ('paragraph_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.paragraph', verbose_name='პარაგრაფი')),
            ],
            options={
                'verbose_name': 'ამბები',
            },
        ),
    ]
