# Generated by Django 4.0.1 on 2022-02-02 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_english', models.CharField(max_length=255, verbose_name='ინგლისური')),
                ('in_georgian', models.CharField(max_length=255, verbose_name='ქართულად')),
                ('datetime', models.DateTimeField(default=False, verbose_name='დამატების თარიღი')),
                ('paragraph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.paragraph', verbose_name='პარაგრაფი')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='მფლობელი')),
            ],
            options={
                'verbose_name': 'ლექსიკონი',
            },
        ),
    ]
